/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import { Code, Skeleton } from "@chakra-ui/react";
export default function Home() {
  return (
    <>
      <Head>
        <title>QUIZ APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Skeleton height={"100vh"}>
          <div>contents wrapped</div>
          <div>won't be visible</div>
        </Skeleton>
      </main>
    </>
  );
}
