import Head from "next/head";
import { Code } from "@chakra-ui/react";
import QuestionCard from "@/components/QuestionCard";
export default function Home() {
  return (
    <>
      <Head>
        <title>QUIZ APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <QuestionCard
          questions={"WHAT IS YOUR NAME"}
          category={"GENERAL"}
          callback={() => {}}
          questionNumber={10}
          totalQuestions={3}
        />
      </main>
    </>
  );
}
