/* eslint-disable react/no-unescaped-entities */
import { QuestionProps } from "@/ineterfaces";
import { getQuestionList } from "@/lib/helper";
import Head from "next/head";
import { totalQuestions, Difficulty } from "@/lib/constant";
import { useState, useEffect } from "react";
import Questioncard from "@/components/QuestionCard";
export default function Home() {
  const [questions, setQuestions] = useState<QuestionProps[]>([]);

  useEffect(() => {
    const fetchQuestions = async () => {
      const questionsList = await getQuestionList(
        totalQuestions,
        Difficulty.HARD
      );
      setQuestions(questionsList);
    };
    fetchQuestions();
  }, []);
  return (
    <>
      <Head>
        <title>QUIZ APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Questioncard questions={""} category={""} callback={() => {}} />
      </main>
    </>
  );
}
